version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/fastapi_dev
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-super-secret-key-here-at-least-32-characters-long-for-testing
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    depends_on:
      - db
      - redis
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fastapi_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: